@extends('layouts.app')
@section('title','Settings')
@section('content')
<p class="mb-6 text-sm text-slate-500">These details appear on every invoice and PDF.</p><form method="POST" action="{{ route('settings.update') }}" enctype="multipart/form-data" class="card max-w-3xl">@csrf @method('PUT')<div class="grid gap-5 sm:grid-cols-2"><label class="field sm:col-span-2">Company name<input name="company_name" value="{{ old('company_name',$settings['company_name'] ?? '') }}"></label><label class="field">Company logo<input type="file" accept="image/*" name="logo" class="file:mr-3 file:rounded file:border-0 file:bg-indigo-50 file:px-3 file:py-1 file:text-indigo-700">@if(!empty($settings['logo']))<img src="{{ asset('storage/'.$settings['logo']) }}" alt="Current company logo" class="mt-2 h-16 w-auto rounded border border-slate-200 p-1"><span class="mt-1 text-xs text-slate-500">Current logo</span>@endif</label><label class="field">Registration number<input name="registration_number" value="{{ old('registration_number',$settings['registration_number'] ?? '') }}"></label><label class="field sm:col-span-2">Address<textarea name="address" rows="3">{{ old('address',$settings['address'] ?? '') }}</textarea></label><label class="field">Phone<input name="phone" value="{{ old('phone',$settings['phone'] ?? '') }}"></label><label class="field">Email<input type="email" name="email" value="{{ old('email',$settings['email'] ?? '') }}"></label><label class="field sm:col-span-2">Terms & conditions<textarea name="terms" rows="5">{{ old('terms',$settings['terms'] ?? '') }}</textarea></label></div><div class="mt-7 flex justify-end"><button class="btn-primary">Save settings</button></div></form>

<div class="card mt-6 max-w-3xl" x-data="bankAccountManager(@js($bankAccounts))"><h2 class="section-title">Bank accounts</h2><p class="mb-5 -mt-3 text-sm text-slate-500">Add every account you accept payment into — you'll pick one per invoice.</p>
<form method="POST" :action="action" class="mb-6 grid gap-4 rounded-lg border border-slate-200 p-4 sm:grid-cols-3">@csrf<input type="hidden" name="_method" :value="editingId ? 'PUT' : 'POST'"><label class="field">Bank name*<input name="bank_name" x-model="form.bank_name" required placeholder="e.g. Maybank"></label><label class="field">Account number*<input name="account_number" x-model="form.account_number" required></label><label class="field">Account holder<input name="account_holder" x-model="form.account_holder" placeholder="Optional"></label><div class="flex gap-3 sm:col-span-3"><button class="btn-primary" x-text="editingId ? 'Update account' : 'Add account'"></button><button type="button" x-show="editingId" @click="cancel()" class="btn-secondary">Cancel</button></div></form>
<div class="divide-y divide-slate-100 rounded-lg border border-slate-200"><template x-for="item in items" :key="item.id"><div class="flex items-center justify-between gap-4 px-4 py-3"><div><p class="font-medium text-slate-800" x-text="item.bank_name"></p><p class="text-sm text-slate-500" x-text="item.account_holder ? `${item.account_number} — ${item.account_holder}` : item.account_number"></p></div><div class="flex shrink-0 gap-3 text-xs font-medium"><button type="button" @click="edit(item)" class="text-indigo-600">Edit</button><form method="POST" :action="`/bank-accounts/${item.id}`" onsubmit="return confirm('Delete this bank account?')"><input type="hidden" name="_token" value="{{ csrf_token() }}"><input type="hidden" name="_method" value="DELETE"><button class="text-rose-600">Delete</button></form></div></div></template><p x-show="!items.length" class="px-4 py-8 text-center text-sm text-slate-400">No bank accounts added yet.</p></div>
</div>
@endsection
